#!/bin/bash

#set -euo pipefail


if [[ $# -lt 1 ]]; then
    echo "Exec file must be specified!"
    exit 1
fi

exec_file=$1
input_dir=./input
expect_dir=./expect

test_ctr=0
error_ctr=0

for file in `find ${input_dir} -type f`
do
    output=$({exec_file} < ${input_dir}/${file})
    expect=$(cat ${expect_dir}/${file})

    if [[ output == expect ]]; then
        echo "Test #${test_ctr} '${file}' --- OK"
    else
        echo "Test #${test_ctr} '${file}' --- FAIL"
        echo "expected '${expect}', got '${output}'"
        echo ""

        ((error_ctr++))
    fi

    ((test_ctr++))
done

echo "TOTAL:"
echo "Conducted ${test_ctr} tests with ${error_ctr} errors."