#!/bin/bash

#set -euo pipefail


if [[ $# -lt 1 ]]; then
    echo "Exec file must be specified!"
    exit 1
fi

exec_file=$1
tests_dir=./test_data
test_ctr=0
error_ctr=0

for input_file in `find ${tests_dir} -name "*.in" -type f`
do
    test=$(echo "${input_file}" | sed 's/.in//')

    output=$(${exec_file} < ${test}.in 2> /dev/null)
    expect=$(cat ${test}.exp)

    if [[ output -eq expect ]]; then
        echo "Test #${test_ctr} '${test}' --- OK"
    else
        echo "Test #${test_ctr} '${test}' --- FAIL"
        echo "expected '${expect}', got '${output}'"
        echo ""

        ((error_ctr++))
    fi

    ((test_ctr++))
done

echo "TOTAL:"
echo "Conducted ${test_ctr} tests with ${error_ctr} errors."