#!/bin/bash

set -u

if [[ $# -lt 2 ]]; then
    echo "Usage:"
    echo "test_e2e <path/to/exec_file> <path/to/test_data>"
    exit 1
fi

exec_file=$1
tests_dir=$2 #./test_data
logfile=test_e2e.log
test_ctr=0
error_ctr=0

echo "Started end-to-end testing..." > ${logfile}

for input_file in `find ${tests_dir} -name "*.in" -type f | sort`
do
    test=$(echo "${input_file}" | sed 's/\.in//')

    echo "" >> ${logfile}
    echo "[test_e2e] Error thread for test #${test_ctr} '${test}':" >> ${logfile}

    output=$(${exec_file} < ${test}.in 2>> ${logfile})
    expect=$(cat ${test}.exp)

    if [[ output -eq expect ]]; then
        echo -e "Test #${test_ctr} '${test}' ---\033[32m OK \033[0m"
    else
        echo -e "Test #${test_ctr} '${test}' ---\033[31m FAIL \033[0m"
        echo "expected '${expect}', got '${output}'"
        echo ""

        ((error_ctr++))
    fi

    ((test_ctr++))
done

echo ""
echo -e "\033[1mTOTAL:\033[0m"
echo "Conducted ${test_ctr} tests with ${error_ctr} errors."
echo "See test_e2e.log for more."